"""oauth tables, and scopes on opaque tokens

Revision ID: 0006_oauth_and_token_scopes
Revises: 0005_invite_codes
Create Date: 2026-07-31

Better Auth's OAuth tables live beside its others, in the `better_auth` schema
migration 0003 created. They are created here rather than by Better Auth's own
CLI so that one tool owns the schema in every environment -- the same rule
0003 established. The CLI (`npm run schema:generate` in auth/) was used only
at development time to produce correct DDL, verbatim below except for two
mechanical changes: schema-qualifying every table name and every
cross-table reference with `better_auth.`, and adding `if not exists` /
`if not exists` guards to match the idempotency convention every other
revision in this directory follows.

Column names are camelCase and MUST stay double-quoted: unquoted, Postgres
folds them to lowercase and Better Auth's queries (which send the camelCase
spelling) stop matching.

Every statement is idempotent, matching the baseline revision's standing rule.
"""
from alembic import op

revision = "0006_oauth_and_token_scopes"
down_revision = "0005_invite_codes"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Generated by `cd auth && npm run schema:generate` against
    # @better-auth/oauth-provider 1.6.25 (auth/src/oauth.js), then
    # schema-qualified and made idempotent. Regenerate rather than hand-edit
    # if the plugin's options change.
    op.execute(
        """
        create table if not exists better_auth."oauthClient" (
            "id" text not null primary key,
            "clientId" text not null unique,
            "clientSecret" text,
            "disabled" boolean,
            "skipConsent" boolean,
            "enableEndSession" boolean,
            "subjectType" text,
            "scopes" jsonb,
            "userId" text references better_auth."user" ("id") on delete cascade,
            "createdAt" timestamptz,
            "updatedAt" timestamptz,
            "name" text,
            "uri" text,
            "icon" text,
            "contacts" jsonb,
            "tos" text,
            "policy" text,
            "softwareId" text,
            "softwareVersion" text,
            "softwareStatement" text,
            "redirectUris" jsonb not null,
            "postLogoutRedirectUris" jsonb,
            "tokenEndpointAuthMethod" text,
            "grantTypes" jsonb,
            "responseTypes" jsonb,
            "public" boolean,
            "type" text,
            "requirePKCE" boolean,
            "referenceId" text,
            "metadata" jsonb
        )
        """
    )

    op.execute(
        """
        create table if not exists better_auth."oauthRefreshToken" (
            "id" text not null primary key,
            "token" text not null unique,
            "clientId" text not null references better_auth."oauthClient" ("clientId") on delete cascade,
            "sessionId" text references better_auth."session" ("id") on delete set null,
            "userId" text not null references better_auth."user" ("id") on delete cascade,
            "referenceId" text,
            "expiresAt" timestamptz not null,
            "createdAt" timestamptz not null,
            "revoked" timestamptz,
            "authTime" timestamptz,
            "scopes" jsonb not null
        )
        """
    )

    op.execute(
        """
        create table if not exists better_auth."oauthAccessToken" (
            "id" text not null primary key,
            "token" text not null unique,
            "clientId" text not null references better_auth."oauthClient" ("clientId") on delete cascade,
            "sessionId" text references better_auth."session" ("id") on delete set null,
            "userId" text references better_auth."user" ("id") on delete cascade,
            "referenceId" text,
            "refreshId" text references better_auth."oauthRefreshToken" ("id") on delete cascade,
            "expiresAt" timestamptz not null,
            "createdAt" timestamptz not null,
            "scopes" jsonb not null
        )
        """
    )

    op.execute(
        """
        create table if not exists better_auth."oauthConsent" (
            "id" text not null primary key,
            "clientId" text not null references better_auth."oauthClient" ("clientId") on delete cascade,
            "userId" text references better_auth."user" ("id") on delete cascade,
            "referenceId" text,
            "scopes" jsonb not null,
            "createdAt" timestamptz not null,
            "updatedAt" timestamptz not null
        )
        """
    )

    op.execute(
        'create index if not exists "oauthClient_userId_idx"'
        ' on better_auth."oauthClient" ("userId")'
    )
    op.execute(
        'create index if not exists "oauthRefreshToken_clientId_idx"'
        ' on better_auth."oauthRefreshToken" ("clientId")'
    )
    op.execute(
        'create index if not exists "oauthRefreshToken_sessionId_idx"'
        ' on better_auth."oauthRefreshToken" ("sessionId")'
    )
    op.execute(
        'create index if not exists "oauthRefreshToken_userId_idx"'
        ' on better_auth."oauthRefreshToken" ("userId")'
    )
    op.execute(
        'create index if not exists "oauthAccessToken_clientId_idx"'
        ' on better_auth."oauthAccessToken" ("clientId")'
    )
    op.execute(
        'create index if not exists "oauthAccessToken_sessionId_idx"'
        ' on better_auth."oauthAccessToken" ("sessionId")'
    )
    op.execute(
        'create index if not exists "oauthAccessToken_userId_idx"'
        ' on better_auth."oauthAccessToken" ("userId")'
    )
    op.execute(
        'create index if not exists "oauthAccessToken_refreshId_idx"'
        ' on better_auth."oauthAccessToken" ("refreshId")'
    )
    op.execute(
        'create index if not exists "oauthConsent_clientId_idx"'
        ' on better_auth."oauthConsent" ("clientId")'
    )
    op.execute(
        'create index if not exists "oauthConsent_userId_idx"'
        ' on better_auth."oauthConsent" ("userId")'
    )

    # Scopes on opaque tokens. The default is every scope, and that is the
    # load-bearing part: tokens already configured on other people's machines
    # get the behaviour they have always had, and only newly minted tokens can
    # be narrower. A default of '{}' would revoke every credential in the
    # field the moment this deployed.
    op.execute(
        "alter table tokens add column if not exists scopes text[]"
        " not null default '{persona:read,persona:propose,persona:write}';"
    )


def downgrade() -> None:
    op.execute("alter table tokens drop column if exists scopes;")
    for table in ("oauthConsent", "oauthAccessToken", "oauthRefreshToken", "oauthClient"):
        op.execute(f'drop table if exists better_auth."{table}" cascade;')
